# Generated by Django 5.0.2 on 2024-02-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bathroom',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='bhk',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
